In [1]:

import pandas as pd

# Create sample data
data = {"Name": ["Alice", "Bob", "Charlie"],
        "Age": [25, 30, 35],
        "Salary": [50000, 60000, 70000]}

df = pd.DataFrame(data)

# Save to CSV
df.to_csv("sample_data.csv", index=False)

# Read the CSV file
df_read = pd.read_csv("sample_data.csv")

# Display data
print(df_read)

# Basic statistics
print("\nSummary statistics:")
print(df_read.describe())

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

Summary statistics:
        Age   Salary
count   3.0      3.0
mean   30.0  60000.0
std     5.0  10000.0
min    25.0  50000.0
25%    27.5  55000.0
50%    30.0  60000.0
75%    32.5  65000.0
max    35.0  70000.0